objects/Project_Defect__c.object
<CustomObject>
    <fields>
        <fullName>Test_Case_Execution_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case Execution Id</label>
        <referenceTo>Test_Case_Execution__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Step_Execution_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Step Execution Id</label>
        <referenceTo>Test_Step_Execution__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the defected Test Step</description>
        <label>Test Step</label>
        <referenceTo>Test_Step__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Test_Case_Execution__c.object
<CustomObject>
    <description>Test Case Execution contains brief details on Test Case along with details of tester who executed the particular Test Case.</description>
    <label>Test Case Execution</label>
    <nameField>
        <displayFormat>TCE-{0000}</displayFormat>
        <label>Test Case Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Executions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Step__c.object
<CustomObject>
    <description>Test Step contains steps to be performed related to a Test Case</description>
    <label>Test Step</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Test Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Step_Execution__c.object
<CustomObject>
    <description>Test Step Execution contains brief details on Test Step and the details of the tester who tested the particular Test Step.</description>
    <fields>
        <fullName>Test_Case_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case Execution</label>
        <referenceTo>Test_Case_Execution__c</referenceTo>
        <relationshipLabel>Test Step Executions</relationshipLabel>
        <relationshipName>Test_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Step</label>
        <referenceTo>Test_Step__c</referenceTo>
        <relationshipLabel>Test Step Executions</relationshipLabel>
        <relationshipName>Test_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Step Execution</label>
    <nameField>
        <displayFormat>TSE-{0000}</displayFormat>
        <label>Test Step Execution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Step Executions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AP_CreateTestCaseExecution.cls
global class AP_CreateTestCaseExecution {
    @InvocableMethod(label='Insert Test Case Execution')
    global static List<List<Project_Defect__c>> invokeTCE(invocableRequest[] reqList){
        List<Test_Step_Execution__c> tse1 = new List<Test_Step_Execution__c>();
        List<Project_Defect__c> def1 = new List<Project_Defect__c>();
        List<List<Project_Defect__c>> wrapper = new List<List<Project_Defect__c>>();
        System.debug('hello'+ reqList[0].def);
        System.debug('hello tse'+ reqList[0].tse);
        tse1 = reqList[0].tse;
        def1 = reqList[0].def;
        if(tse1 != null &&  def1 != null){
        Map<Id,Test_Step_Execution__c> a = new Map<Id,Test_Step_Execution__c>();
        for(Test_Step_Execution__c t : tse1){
            a.put(t.Test_Step__c,t);
        }
        for(Project_Defect__c d : def1){
            System.debug('defect before value'+d);
            Test_Step_Execution__c var = a.get(d.Test_Step__c);
            if(var!= null){
                d.Test_Step_Execution_Id__c = var.Id;
                d.Test_Case_Execution_Id__c = var.Test_Case_Execution__c;
            }
            System.debug('defect after value'+d);
        }
        List<Project_Defect__c> responseList=new List<Project_Defect__c>();
        for (Project_Defect__c defect: def1 ){       
        responseList.add(defect);       
    	}
        wrapper.add(responseList);
    	
        }
		return wrapper;
    }
    global class invocableRequest{
        @InvocableVariable
        global List<Test_Step_Execution__c> tse;
        
        @InvocableVariable
        global List<Project_Defect__c> def;
    }

}