objects/Project_Defect__c.object
<CustomObject>
    <fields>
        <fullName>Test_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Stores the defected Test Step</description>
        <label>Test Step</label>
        <referenceTo>Test_Step__c</referenceTo>
        <relationshipLabel>Defects</relationshipLabel>
        <relationshipName>Defects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

objects/Test_Case__c.object
<CustomObject>
    <description>Test Case contains a brief overview of Release, Capability, User Stories, estimation for Writing and Executing Test Steps.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Store brief description of the Test Case</description>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Stores Releases of given application</description>
        <label>Release</label>
        <referenceTo>Project_Release__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Scenario</label>
        <referenceTo>Test_Scenario__c</referenceTo>
        <relationshipLabel>Test Cases</relationshipLabel>
        <relationshipName>Test_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Test Case</label>
    <nameField>
        <displayFormat>TC-{0000}</displayFormat>
        <label>Test Case Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Case_Execution__c.object
<CustomObject>
    <description>Test Case Execution contains brief details on Test Case along with details of tester who executed the particular Test Case.</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Test Case</description>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Release__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Release version of the Test Case</description>
        <label>Release</label>
        <referenceTo>Project_Release__c</referenceTo>
        <relationshipLabel>Test Case Executions</relationshipLabel>
        <relationshipName>Test_Case_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Not Yet Executed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Test Case which is related to this Test Case Execution</description>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Case Executions</relationshipLabel>
        <relationshipName>Test_Case_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Scenario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Scenario</label>
        <referenceTo>Test_Scenario__c</referenceTo>
        <relationshipLabel>Test Case Executions</relationshipLabel>
        <relationshipName>Test_Case_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <label>Test Case Execution</label>
    <nameField>
        <displayFormat>TCE-{0000}</displayFormat>
        <label>Test Case Execution</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Case Executions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Test_Scenario__c.object
<CustomObject>
    <description>Test Scenario acts as a template for Test Case</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scenario__c</fullName>
        <label>Scenario</label>
        <type>TextArea</type>
    </fields>
    <label>Test Scenario</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Test Scenario Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Scenarios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Step__c.object
<CustomObject>
    <description>Test Step contains steps to be performed related to a Test Case</description>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of Test Step</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <description>Expected result when the Test Step is performed</description>
        <label>Expected Result</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case</label>
        <referenceTo>Test_Case__c</referenceTo>
        <relationshipLabel>Test Steps</relationshipLabel>
        <relationshipName>Test_Steps</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Step</label>
    <nameField>
        <displayFormat>TS-{0000}</displayFormat>
        <label>Test Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Test_Step_Execution__c.object
<CustomObject>
    <description>Test Step Execution contains brief details on Test Step and the details of the tester who tested the particular Test Step.</description>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <description>Actual result obtained after executing the Test Step</description>
        <label>Actual Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expected_Result__c</fullName>
        <label>Expected Result</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_TSE__c</fullName>
        <defaultValue>&quot;Not Yet Executed&quot;</defaultValue>
        <description>Status of the test step if it is passed failed or not yet executed</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Executed</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of Test Step Execution to know if it  is pass or fail</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Test_Case_Execution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Case Execution</label>
        <referenceTo>Test_Case_Execution__c</referenceTo>
        <relationshipLabel>Test Step Executions</relationshipLabel>
        <relationshipName>Test_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Test_Step__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test Step</label>
        <referenceTo>Test_Step__c</referenceTo>
        <relationshipLabel>Test Step Executions</relationshipLabel>
        <relationshipName>Test_Step_Executions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Test Step Execution</label>
    <nameField>
        <displayFormat>TSE-{0000}</displayFormat>
        <label>Test Step Execution Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Test Step Executions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AP_InsertDefectDocumentTest.cls
@isTest
//This test class is used for two apex classes AP_CreateTestCaseExecution and AP_InsertDefectDocument
global class AP_InsertDefectDocumentTest {
    @isTest
    static void invocableMethod(){
        Project2__c project = new Project2__c(Name = 'Test Project');
        insert project;
        Project2__c projectID = [SELECT Id FROM Project2__c WHERE Name='Test Project']; 
        Project_Release__c release = new Project_Release__c(Name = 'Release 1', StartDate__c =date.parse('09/02/2020'), ReleaseDate__c=date.parse('11/02/2020'), Project__c =projectID.Id);
        insert release;
        Project_Release__c releaseID = [SELECT Id FROM Project_Release__c WHERE Name='Release 1']; 
        Test_Scenario__c testScenario = new Test_Scenario__c(Scenario__c = 'Test Scenario');
        insert testScenario;
        Test_Case__c testCase = new Test_Case__c(Description__c = 'Test Case', Release__c = releaseID.id);
        insert testCase;
        Test_Case__c testCaseID = [SELECT Id FROM Test_Case__c WHERE Id=:testCase.Id]; 
        List<Test_Step__c> testStep = new List<Test_Step__c>{
            new Test_Step__c(
                     Test_Case__c=testCaseID.id,
                        Role__c='Human Resource',
                        Description__c= 'Login to salesforce', 
                        Expected_Result__c= 'Home page displayed'
                    )
                };
        insert testStep;
        Test_Step__c testStepID = [SELECT Id FROM Test_Step__c WHERE Test_Case__c=:testCaseID.id];
        Test_Case_Execution__c testCaseExecution = new Test_Case_Execution__c(Test_Case__c = testCaseID.id);
        insert testCaseExecution;
        Test_Case_Execution__c tceID = [SELECT Id FROM Test_Case_Execution__c WHERE Test_Case__c=:testCaseID.id]; 
        List<Test_Step_Execution__c> testStepExecution = new List<Test_Step_Execution__c>{
            new Test_Step_Execution__c(
                     Test_Step__c = testStepID.id,
                        Role__c = 'Human Resource',
                        Description__c = 'Login to salesforce', 
                        Expected_Result__c = 'Home page displayed',
                		Actual_Result__c = 'Home page not displayed',
                		Status_TSE__c = 'Failed',
                		Test_Case_Execution__c = tceID.id
                    )
                };
        insert testStepExecution;
        List<Project_Defect__c> defect = new List<Project_Defect__c>{
            new Project_Defect__c(
                     Test_Step__c = testStepID.id,
                        ActualResult__c = 'Human Resource',
                        StepToReproduce__c = 'Login to salesforce', 
                		DetectedEnvironment__c = 'DEV',
                		DetectionDate__c = date.parse('11/02/2020'),
                        ExpectedResult__c = 'Home page displayed',
                		Status__c = 'New',
                		Title__c = 'Unable to Login',
                		Type__c = 'Defect',
                		ShortDescription__c = 'Login to salesforce',
                		Severity__c = 'High'
                    )
                };
        insert defect;
        ContentVersion content=new ContentVersion(); 
        content.Title='Header_Picture1'; 
        content.PathOnClient='/' + content.Title + '.jpg'; 
        Blob bodyBlob=Blob.valueOf('Unit Test ContentVersion Body'); 
        content.VersionData=bodyBlob; 
        content.origin = 'H';
        insert content;
        List<String> conDoc = new List<String>();
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId=testStepID.id;
        contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid;
        conDoc.add(contentlink.contentdocumentid=[select contentdocumentid from contentversion where id =: content.id].contentdocumentid);
        contentlink.ShareType = 'V';
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
        
        List<ContentVersion> conDocID = [SELECT ContentDocumentId FROM ContentVersion WHERE Title = 'Header_Picture1'];
        
        List<AP_CreateTestCaseExecution.invocableRequest> invocableReqList = new List<AP_CreateTestCaseExecution.invocableRequest>();
        AP_CreateTestCaseExecution.invocableRequest request = new AP_CreateTestCaseExecution.invocableRequest();
        request.tse = testStepExecution;
        request.def = defect;
        invocableReqList.add(request);
        
        List<AP_InsertDefectDocument.invocableRequest> invocableReqList2 = new List<AP_InsertDefectDocument.invocableRequest>();
        AP_InsertDefectDocument.invocableRequest request2 = new AP_InsertDefectDocument.invocableRequest();
        request2.defectedRecords = defect;
        request2.contentDocID = conDoc;
        invocableReqList2.add(request2);
        
        Test.startTest();
     	AP_CreateTestCaseExecution.invokeTCE(invocableReqList);
        AP_InsertDefectDocument.invokeTCE(invocableReqList2);
     	Test.stopTest();
    }

}